import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { QRCodeSVG } from 'qrcode.react';
import { analyzeAudioFile } from '../lightSync/audioAnalyzer';
import { generateLightTimeline, type LightTimeline } from '../lightSync/timeline';
import { watchShow, updateShow, type Show } from '../firebase/shows';
import { watchParticipants, type ParticipantInfo } from '../firebase/participants';
import { syncShowStats, watchScanCount, watchShowStats, type ShowStats } from '../firebase/analytics';
import { watchSportsGame, type SportsGame, getSportsLightColor } from '../firebase/sportsGame';
import SportsInteractions from './SportsInteractions';

const PUBLIC_APP_URL = (import.meta.env.VITE_PUBLIC_APP_URL || 'https://lightsync-two.vercel.app').replace(/\/$/, '');
function getAudioMimeType(file: File) { const n = file.name.toLowerCase(); if (n.endsWith('.mp3') || n.endsWith('.mpeg')) return 'audio/mpeg'; if (n.endsWith('.m4a') || n.endsWith('.mp4')) return 'audio/mp4'; if (n.endsWith('.wav')) return 'audio/wav'; if (n.endsWith('.ogg') || n.endsWith('.oga')) return 'audio/ogg'; if (n.endsWith('.webm')) return 'audio/webm'; if (n.endsWith('.aac')) return 'audio/aac'; if (n.endsWith('.flac')) return 'audio/flac'; return file.type || 'audio/mpeg'; }
function formatTime(seconds: number) { if (!Number.isFinite(seconds) || seconds < 0) return '0:00'; const total = Math.floor(seconds); return `${Math.floor(total / 60)}:${(total % 60).toString().padStart(2, '0')}`; }

export default function EventControl() {
  const navigate = useNavigate(); const { eventId } = useParams();
  const [event, setEvent] = useState<Show | null>(null); const [game, setGame] = useState<SportsGame | null>(null); const [loaded, setLoaded] = useState(false); const [participantCount, setParticipantCount] = useState(0); const [starting, setStarting] = useState(false);
  const [songName, setSongName] = useState(''); const [songFile, setSongFile] = useState<File | null>(null); const [songUrl, setSongUrl] = useState<string | null>(null); const [analyzing, setAnalyzing] = useState(false); const [analysisMessage, setAnalysisMessage] = useState(''); const [generatedTimeline, setGeneratedTimeline] = useState<LightTimeline | null>(null); const [countdown, setCountdown] = useState<number | null>(null); const [songCurrentTime, setSongCurrentTime] = useState(0); const [songDuration, setSongDuration] = useState(0);
  const [customColor, setCustomColor] = useState('#FFFFFF');
  const [stats, setStats] = useState<ShowStats>({ totalScans: 0, totalJoined: 0, peakConnected: 0 });
  const audioRef = useRef<HTMLAudioElement | null>(null); const startTimerRef = useRef<number | null>(null); const countdownTimerRef = useRef<number | null>(null);

  useEffect(() => { if (!eventId) return; const stopShowWatch = watchShow(eventId, show => { setEvent(show); setLoaded(true); }); const stopParticipantsWatch = watchParticipants(eventId, participants => { setParticipantCount(Object.values(participants).filter((p: ParticipantInfo) => p.connected === true).length); }); const stopStatsWatch = watchShowStats(eventId, setStats); const stopScanWatch = watchScanCount(eventId, count => setStats(current => ({ ...current, totalScans: count }))); const stopGameWatch = watchSportsGame(eventId, setGame); return () => { stopShowWatch(); stopParticipantsWatch(); stopStatsWatch(); stopScanWatch(); stopGameWatch(); }; }, [eventId]);
  useEffect(() => { if (event?.screenLightColor) setCustomColor(event.screenLightColor); }, [event?.screenLightColor]);
  useEffect(() => { if (!eventId || !game?.homeTeam.primaryColor) return; document.documentElement.style.setProperty('--ls-accent', game.homeTeam.primaryColor); document.documentElement.style.setProperty('--ls-accent-2', game.awayTeam?.primaryColor || game.homeTeam.primaryColor); return () => { document.documentElement.style.removeProperty('--ls-accent'); document.documentElement.style.removeProperty('--ls-accent-2'); }; }, [eventId, game?.homeTeam.primaryColor, game?.awayTeam?.primaryColor]);
  useEffect(() => { if (!eventId) return; void syncShowStats(eventId, stats.totalScans, participantCount, participantCount); }, [eventId, stats.totalScans, participantCount]);
  useEffect(() => () => { if (startTimerRef.current !== null) window.clearTimeout(startTimerRef.current); if (countdownTimerRef.current !== null) window.clearInterval(countdownTimerRef.current); audioRef.current?.pause(); if (songUrl) URL.revokeObjectURL(songUrl); }, [songUrl]);

  function chooseSong(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; audioRef.current?.pause(); if (songUrl) URL.revokeObjectURL(songUrl); const url = URL.createObjectURL(new Blob([file], { type: getAudioMimeType(file) })); const audio = new Audio(url); audio.preload = 'auto'; audio.volume = 1; audio.addEventListener('loadedmetadata', () => setSongDuration(audio.duration)); audio.addEventListener('timeupdate', () => setSongCurrentTime(audio.currentTime)); audio.addEventListener('ended', () => { setSongCurrentTime(audio.duration); if (eventId) void updateShow(eventId, { status: 'finished', showStartTime: null }).then(() => setAnalysisMessage('Show finished automatically.')).catch(error => { console.error('Could not finish show automatically:', error); setAnalysisMessage('Song ended, but the show status could not be updated.'); }); }); audioRef.current = audio; setSongFile(file); setSongName(file.name); setSongUrl(url); setGeneratedTimeline(null); setAnalysisMessage(''); setCountdown(null); setSongCurrentTime(0); setSongDuration(0); }
  async function analyzeSong() { if (!songFile) return setAnalysisMessage('Please select an audio file first.'); setAnalyzing(true); setAnalysisMessage('Analyzing music...'); try { const analysis = await analyzeAudioFile(songFile); setGeneratedTimeline(generateLightTimeline(analysis.beats)); setAnalysisMessage(`Analysis complete — ${analysis.beats.length} beats detected.`); } catch (error) { console.error(error); setGeneratedTimeline(null); setAnalysisMessage('Could not analyze this audio file.'); } finally { setAnalyzing(false); } }
  async function startShow() { const audio = audioRef.current; if (!eventId || !generatedTimeline || !audio) { setAnalysisMessage(!generatedTimeline ? 'Analyze the song before starting the show.' : 'Please select the song again.'); return; } setStarting(true); setAnalysisMessage(''); if (startTimerRef.current !== null) window.clearTimeout(startTimerRef.current); if (countdownTimerRef.current !== null) window.clearInterval(countdownTimerRef.current); try { audio.pause(); audio.currentTime = 0; audio.volume = 0; await audio.play(); const startTime = Date.now() + 5000; await updateShow(eventId, { status: 'running', showStartTime: startTime, lightTimeline: generatedTimeline }); setSongCurrentTime(0); setCountdown(5); countdownTimerRef.current = window.setInterval(() => setCountdown(current => { if (current === null || current <= 1) { if (countdownTimerRef.current !== null) window.clearInterval(countdownTimerRef.current); countdownTimerRef.current = null; return null; } return current - 1; }), 1000); const delay = Math.max(0, startTime - Date.now()); startTimerRef.current = window.setTimeout(() => { startTimerRef.current = null; audio.currentTime = 0; audio.volume = 1; setSongCurrentTime(0); }, delay); } catch (error) { console.error('Could not start show:', error); audio.pause(); audio.volume = 1; setCountdown(null); setAnalysisMessage(error instanceof Error && error.name === 'NotAllowedError' ? 'Audio was blocked. Press Play once in the browser audio player, then try Start Show again.' : 'Could not start the show. Check the selected audio file and try again.'); } finally { setStarting(false); } }
  async function stopShow() { if (!eventId) return; if (startTimerRef.current !== null) window.clearTimeout(startTimerRef.current); if (countdownTimerRef.current !== null) window.clearInterval(countdownTimerRef.current); startTimerRef.current = null; countdownTimerRef.current = null; setCountdown(null); if (audioRef.current) { audioRef.current.pause(); audioRef.current.volume = 1; audioRef.current.currentTime = 0; } setSongCurrentTime(0); setAnalysisMessage('Stopping show...'); try { await updateShow(eventId, { status: 'finished', showStartTime: null }); setAnalysisMessage('Show finished.'); } catch (error) { console.error(error); setAnalysisMessage('Could not finish the show. Check the Firebase rules and organizer account.'); } }
  async function changeScreenColor(color: string) { if (!/^#[0-9a-fA-F]{6}$/.test(color) || !eventId) return; try { const normalized = color.toUpperCase(); await updateShow(eventId, { screenLightColor: normalized }); setCustomColor(normalized); } catch (error) { console.error(error); setAnalysisMessage('Could not change the audience screen color.'); } }
  function applyCustomColor() { const value = customColor.trim().startsWith('#') ? customColor.trim() : `#${customColor.trim()}`; if (!/^#[0-9a-fA-F]{6}$/.test(value)) { setAnalysisMessage('Enter a valid 6-digit HEX color, for example #FFFFFF.'); return; } setAnalysisMessage(''); void changeScreenColor(value); }

  if (!loaded) return <main className="ls-shell"><div className="ls-card ls-event-loading">Loading event...</div></main>;
  if (!event || !eventId) return <main className="ls-shell"><div className="ls-card ls-event-loading"><h2>Event not found</h2><button className="ls-button ls-secondary" onClick={() => navigate('/admin')}>BACK TO DASHBOARD</button></div></main>;
  const running = event.status === 'running'; const joinUrl = `${PUBLIC_APP_URL}/join/${eventId}`; const startDisabled = starting || running || !songFile || !generatedTimeline; const stopDisabled = starting || (!running && countdown === null); const progress = songDuration > 0 ? Math.min(100, Math.max(0, (songCurrentTime / songDuration) * 100)) : 0; const screenColor = /^#[0-9a-fA-F]{6}$/.test(event.screenLightColor || '') ? event.screenLightColor! : (game ? getSportsLightColor(game) : '#FFFFFF');
  const homeColor = game?.homeTeam.primaryColor || '#FFFFFF'; const awayColor = game?.awayTeam.primaryColor || homeColor;

  return <main className="ls-shell ls-event-shell" style={{ '--ls-accent': homeColor, '--ls-accent-2': awayColor } as React.CSSProperties}>
    <header className="ls-header ls-event-header"><div><div className="ls-brand">LIGHTSYNC</div><p className="ls-eyebrow">SPORTS EVENT CONTROL</p></div><button type="button" className="ls-button ls-secondary" onClick={() => navigate('/admin')}>BACK TO EVENTS</button></header>
    <section className="ls-event-titlebar"><div><p className="ls-eyebrow">{game?.sport?.toUpperCase() || 'SPORTS EVENT'}</p><h1>{event.name}</h1><p className="ls-muted">{event.venue} &middot; {event.date}</p></div><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><div className={`ls-live-pill ${running ? 'is-running' : ''}`}><span />{running ? 'SHOW RUNNING' : event.status === 'finished' ? 'FINISHED' : 'WAITING'}</div></div></section>
    {game && <div className="ls-matchup" style={{ maxWidth: 1200, margin: '0 auto 18px' }}><div className="ls-matchup-side" style={{ '--side-color': homeColor } as React.CSSProperties}><strong>{game.homeTeam.name}</strong><small>HOME</small></div><div className="ls-matchup-vs">VS</div><div className="ls-matchup-side" style={{ '--side-color': awayColor } as React.CSSProperties}><strong>{game.awayTeam.name}</strong><small>AWAY</small></div></div>}
    <section className="ls-show-id-card"><div><span className="ls-eyebrow">EVENT ID</span><strong>{eventId}</strong></div><button type="button" className="ls-copy-id" onClick={() => void navigator.clipboard?.writeText(eventId)}>COPY ID</button></section>
    <div className="ls-group"><div className="ls-group-heading"><span className="ls-group-bar" /><div><h2>Overview</h2><span>Access &amp; live results</span></div></div><div className="ls-overview-grid">
      <div className="ls-card ls-qr-card"><div className="ls-section-title"><div><p className="ls-eyebrow">AUDIENCE ACCESS</p><h2>Scan to Join</h2></div></div><button type="button" onClick={() => window.open(`/audience/${eventId}`, '_blank', 'noopener,noreferrer')} style={{ width: '100%', cursor: 'pointer', border: 0, background: 'transparent', padding: 0 }} aria-label="Open QR audience screen"><div className="ls-qr-frame"><div className="ls-qr-corner" /><QRCodeSVG value={joinUrl} size={220} bgColor="#ffffff" fgColor="#050505" level="H" /></div></button><p className="ls-qr-url">{joinUrl}</p><p className="ls-muted ls-qr-help">Click the QR code to open the full-screen audience display.</p><button type="button" className="ls-button ls-primary" style={{ width: '100%', marginTop: 14 }} onClick={() => window.open(`/audience/${eventId}`, '_blank', 'noopener,noreferrer')}>OPEN AUDIENCE SCREEN</button></div>
      <div className="ls-card ls-audience-card"><p className="ls-eyebrow">LIVE AUDIENCE</p><div className="ls-audience-number">{participantCount}</div><div className="ls-audience-label">CONNECTED PHONES</div><div className="ls-audience-indicator"><span /> Live connection count</div></div>
      <div className="ls-card"><p className="ls-eyebrow">EVENT ANALYTICS</p><h2>Audience results</h2><div className="ls-analytics-list"><div className="ls-analytics-row"><span className="ls-muted">QR SCANS</span><strong>{stats.totalScans}</strong></div><div className="ls-analytics-row"><span className="ls-muted">TOTAL JOINED</span><strong>{stats.totalJoined}</strong></div><div className="ls-analytics-row"><span className="ls-muted">PEAK CONNECTED</span><strong>{stats.peakConnected}</strong></div></div></div>
    </div></div>
    <div className="ls-group"><div className="ls-group-heading"><span className="ls-group-bar" /><div><h2>Program</h2><span>Soundtrack &amp; show control</span></div></div><div className="ls-program-grid">
      <div className="ls-card"><div className="ls-section-title"><div><p className="ls-eyebrow">MUSIC & TIMELINE</p><h2>Show soundtrack</h2></div></div><label className="ls-upload"><span>{songFile ? 'CHANGE SONG' : 'SELECT SONG'}</span><input type="file" accept="audio/*,.mp3,.mpeg,.m4a,.wav,.ogg,.webm,.aac,.flac" onChange={chooseSong} /></label>{songName && <div className="ls-song-name"><span className="ls-song-icon">&#9834;</span><div><strong>{songName}</strong><small>{generatedTimeline ? 'Light timeline ready' : 'Ready to analyze'}</small></div></div>}<div className="ls-song-progress" aria-label="Song progress"><div className="ls-progress-track"><div className="ls-progress-fill" style={{ width: `${progress}%` }} /></div><div className="ls-time-row"><span>{formatTime(songCurrentTime)}</span><span>{formatTime(songDuration)}</span></div></div><button type="button" className="ls-button ls-secondary ls-full-button" onClick={analyzeSong} disabled={!songFile || analyzing}>{analyzing ? 'ANALYZING...' : 'ANALYZE SONG'}</button>{analysisMessage && <p className={`ls-analysis-message ${generatedTimeline ? 'is-ready' : ''}`}>{analysisMessage}</p>}{generatedTimeline && <div className="ls-ready-badge">&check; LIGHT TIMELINE READY</div>}</div>
      <div className="ls-card"><div className="ls-section-title"><div><p className="ls-eyebrow">SHOW CONTROL</p><h2>{countdown !== null ? `Starting in ${countdown}` : running ? 'Show is live' : event.status === 'finished' ? 'Show finished' : 'Ready when you are'}</h2></div></div><p className="ls-muted">The soundtrack stays on this computer. Phones receive only synchronized light instructions.</p><div className="ls-control-actions"><button type="button" className="ls-button ls-primary ls-control-main" onClick={startShow} disabled={startDisabled}>{starting ? 'STARTING...' : 'START SHOW'}</button><button type="button" className="ls-button ls-stop" onClick={stopShow} disabled={stopDisabled}>STOP SHOW</button></div><p className="ls-stop-note">STOP SHOW stops the music and marks the event as finished.</p></div>
    </div></div>
    <div className="ls-group"><div className="ls-group-heading"><span className="ls-group-bar" /><div><h2>Audience Engagement</h2><span>Screen color &amp; interactions</span></div></div><div className="ls-engage-grid">
      <div className="ls-card"><div className="ls-section-title"><div><p className="ls-eyebrow">AUDIENCE SCREEN</p><h2>Phone screen light color</h2></div><div className="ls-current-color-swatch" style={{ background: screenColor, boxShadow: `0 0 28px ${screenColor}66` }} aria-label={`Current screen color ${screenColor}`} /></div><p className="ls-muted">This controls the color shown on connected phones when their synchronized light is ON. The physical flashlight remains white.</p><div className="ls-screen-color-row"><label className="ls-color-chip-field"><input type="color" value={screenColor} onChange={e => void changeScreenColor(e.target.value)} aria-label="Choose screen light color" /><span>COLOR PALETTE</span></label><input className="ls-hex-input" value={customColor} onChange={e => setCustomColor(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') applyCustomColor(); }} aria-label="Custom HEX color" placeholder="#FFFFFF" maxLength={7} /><button type="button" className="ls-button ls-secondary" onClick={applyCustomColor}>APPLY HEX</button></div></div>
      <SportsInteractions embedded />
    </div></div>
  </main>;
}
