import { Link } from 'react-router-dom';
import '../styles/nextted.css';

function Nav() {
  return <header className="nextted-nav"><Link to="/" className="nextted-logo">NEXTT<span>ED</span></Link><nav className="nextted-nav-links"><Link to="/mission">Misyon & Vizyon</Link><Link to="/projects">Projeler</Link><Link to="/contact">İletişim</Link><Link to="/admin" className="nextted-light-btn">LightSync'i Aç</Link></nav></header>;
}

export default function NexttedHome() {
  return <div className="nextted-site"><Nav /><main>
    <section className="nextted-hero"><div className="nextted-container"><p className="nextted-kicker">Technology · Education · Design</p><h1>Gerçek problemlerin etrafında <em>dijital deneyimler</em> tasarlıyoruz.</h1><p className="nextted-lead">Nextted; gerçek deneyimlerden doğan dijital ürünler, kullanıcı deneyimleri ve yeni fikirler üzerinde çalışan bir teknoloji ve tasarım stüdyosudur.</p><div className="nextted-actions"><Link to="/projects" className="nextted-btn nextted-btn-primary">Çalışmalarımıza bakın</Link><Link to="/mission" className="nextted-btn nextted-btn-secondary">Nextted neden var?</Link></div></div></section>
    <section className="nextted-section"><div className="nextted-container"><div className="nextted-section-head"><h2>Ne yapıyoruz?</h2><p>İnsanlar, teknoloji ve işlerin gerçekte nasıl yürüdüğü arasındaki alanla ilgileniyoruz. Önce problemi anlıyor, sonra ürünü bu probleme göre tasarlıyoruz.</p></div><div className="nextted-project-grid"><Link to="/projects#koza" className="nextted-project-card"><span className="nextted-project-no">01 / ÜRÜN TASARIMI</span><h3>Koza Halı</h3><p>Calvin Klein üretici ve distribütörü tarafından kullanılan canlı bir iş uygulaması için B2B iş akışı ve UX/UI tasarımı.</p><span className="nt-tag">Canlı ürün →</span></Link><Link to="/projects#enyakit" className="nextted-project-card"><span className="nextted-project-no">02 / UX ARAŞTIRMASI</span><h3>En Yakıt</h3><p>THY iş birliği yolculuğunu da kapsayan elektrikli araç şarj deneyimi için kullanıcı araştırması, saha çalışması ve UX/UI.</p><span className="nt-tag">Geliştiriliyor →</span></Link><Link to="/projects#lightsync" className="nextted-project-card"><span className="nextted-project-no">03 / SPOR TEKNOLOJİSİ</span><h3>LightSync</h3><p>Yıllarca canlı spor etkinliklerinin içinde çalışarak geliştirdiğimiz bir taraftar etkileşim platformu.</p><span className="nt-tag">Ürünümüz →</span></Link></div></div></section>
    <section className="nextted-section"><div className="nextted-container"><div className="nextted-story"><h2>Problemin içinden geldik.</h2><div><p>Profesyonel spordaki çalışmalarımız LightSync'ten yıllar önce başladı. <strong>Gaziantep Basketbol</strong>, <strong>Adam Voleybol</strong>, <strong>Gaziantep FK</strong> ve 2026–2027 sezonunda <strong>KBB Kipaş İstiklal Basketbol</strong> ile müzik, ışık, anons ve maç günü operasyonlarında çalıştık.</p><p>Bu ortamların içinde olmak, canlı bir maçın ne kadar daha etkileşimli olabileceğini gösterdi. LightSync, bu deneyimi değiştirmek için geliştirdiğimiz ilk ürün.</p><Link to="/mission" className="nextted-btn nextted-btn-secondary">Hikâyemizi okuyun →</Link></div></div><div className="nextted-stat-row"><div className="nextted-stat"><b>1</b><span>Geliştirdiğimiz spor teknolojisi ürünü</span></div><div className="nextted-stat"><b>2</b><span>Gaziantep'teki büyük ürün tasarımı projesi</span></div><div className="nextted-stat"><b>4</b><span>Deneyimimizle bağlantılı spor organizasyonu</span></div><div className="nextted-stat"><b>∞</b><span>Deneyimi daha iyi hale getirmek için alan</span></div></div></div></section>
  </main><footer className="nextted-footer"><div className="nextted-container nextted-footer-inner"><span>© {new Date().getFullYear()} Nextted</span><span>Technology. Education. Design.</span></div></footer></div>;
}
