import { Link } from 'react-router-dom';
import '../styles/nextted.css';

function Nav() {
  return <header className="nextted-nav"><Link to="/" className="nextted-logo">NEXTT<span>ED</span></Link><nav className="nextted-nav-links"><Link to="/mission">Mission & Vision</Link><Link to="/projects">Projects</Link><Link to="/contact">Contact</Link><Link to="/admin" className="nextted-light-btn">Open LightSync</Link></nav></header>;
}

export default function NexttedHome() {
  return <div className="nextted-site"><Nav /><main>
    <section className="nextted-hero"><div className="nextted-container"><p className="nextted-kicker">Technology · Education · Design</p><h1>We build digital experiences around <em>real problems.</em></h1><p className="nextted-lead">Nextted is a technology and design studio working on digital products, user experiences and new ideas born from real-world experience.</p><div className="nextted-actions"><Link to="/projects" className="nextted-btn nextted-btn-primary">See our work</Link><Link to="/mission" className="nextted-btn nextted-btn-secondary">Why Nextted?</Link></div></div></section>
    <section className="nextted-section"><div className="nextted-container"><div className="nextted-section-head"><h2>What we do</h2><p>We are interested in the space between people, technology and the way things actually work. That means understanding the problem first, then designing the product around it.</p></div><div className="nextted-project-grid"><Link to="/projects#koza" className="nextted-project-card"><span className="nextted-project-no">01 / PRODUCT DESIGN</span><h3>Koza Halı</h3><p>B2B workflow mapping and UX/UI for a live business application used in the carpet industry.</p><span className="nt-tag">Live product →</span></Link><Link to="/projects#enyakit" className="nextted-project-card"><span className="nextted-project-no">02 / UX RESEARCH</span><h3>En Yakıt</h3><p>User research, fieldwork and UX/UI for an EV charging experience, including the THY partnership journey.</p><span className="nt-tag">In development →</span></Link><Link to="/projects#lightsync" className="nextted-project-card"><span className="nextted-project-no">03 / SPORTS TECHNOLOGY</span><h3>LightSync</h3><p>An audience engagement platform built from years of working inside live sports events.</p><span className="nt-tag">Our product →</span></Link></div></div></section>
    <section className="nextted-section"><div className="nextted-container"><div className="nextted-story"><h2>We came from inside the problem.</h2><div><p>Our work in professional sports started years before LightSync. We have worked on music, lighting, announcing and game-day operations with <strong>Gaziantep Basketbol</strong>, <strong>Adam Voleybol</strong>, <strong>Gaziantep FK</strong> and, for the 2026–2027 season, <strong>KBB Kipaş İstiklal Basketbol</strong>.</p><p>Being inside those environments showed us how much more engaging a live game could be. LightSync is the first product we are building to change that experience.</p><Link to="/mission" className="nextted-btn nextted-btn-secondary">Read our story →</Link></div></div><div className="nextted-stat-row"><div className="nextted-stat"><b>3+</b><span>Sports organizations currently connected to our experience</span></div><div className="nextted-stat"><b>2</b><span>Major product design projects in Gaziantep</span></div><div className="nextted-stat"><b>1</b><span>Sports technology product being built by us</span></div><div className="nextted-stat"><b>∞</b><span>Room to make the experience better</span></div></div></div></section>
  </main><footer className="nextted-footer"><div className="nextted-container nextted-footer-inner"><span>© {new Date().getFullYear()} Nextted</span><span>Technology. Education. Design.</span></div></footer></div>;
}
