import { Link } from 'react-router-dom';
import '../styles/nextted.css';

function Nav() { return <header className="nextted-nav"><Link to="/" className="nextted-logo">NEXTT<span>ED</span></Link><nav className="nextted-nav-links"><Link to="/mission">Mission & Vision</Link><Link to="/projects">Projects</Link><Link to="/contact">Contact</Link><Link to="/admin" className="nextted-light-btn">Open LightSync</Link></nav></header>; }

export default function Projects() { return <div className="nextted-site"><Nav /><main><section className="nextted-page-head"><div className="nextted-container"><p className="nextted-kicker">Selected work</p><h1>Projects built around real users and real environments.</h1><p>These projects are different in industry and scale, but they share the same approach: understand the workflow, understand the people, then design the product.</p></div></section><section className="nextted-container">
  <article id="koza" className="nextted-case"><div className="nextted-case-meta"><span>01 · Koza Halı</span><span>Product Design / UX/UI</span></div><h2>A B2B experience built around the actual workflow.</h2><p className="nextted-case-intro">For Koza Halı, a manufacturer and distributor working with major international brands, the challenge was not simply making a nicer interface. We mapped how the B2B operation worked and used that understanding to make the application easier to use.</p><div className="nextted-case-grid"><div className="nextted-case-block"><h3>Workflow mapping</h3><p>We mapped the existing process to understand what users needed to do, where they moved between steps and where the digital experience created friction.</p></div><div className="nextted-case-block"><h3>User experience</h3><p>The application structure was redesigned around the way people actually work instead of forcing users to adapt to the interface.</p></div><div className="nextted-case-block"><h3>Outcome</h3><p>Nextted prepared the UX and UI for the B2B application. The product is currently live.</p></div></div></article>
  <article id="enyakit" className="nextted-case"><div className="nextted-case-meta"><span>02 · En Yakıt</span><span>UX Research / UX/UI</span></div><h2>Designing the EV charging journey from the field.</h2><p className="nextted-case-intro">For En Yakıt, we looked at the complete charging experience rather than only the screens inside the app. This included the user journey, the charging flow and the experience around the company's collaboration with THY.</p><div className="nextted-case-grid"><div className="nextted-case-block"><h3>App mapping</h3><p>We mapped how the application works and how different journeys connect, including the additional context created by the THY partnership.</p></div><div className="nextted-case-block"><h3>Field research</h3><p>We went into the field to understand what users actually faced while using EV chargers and where the digital experience could be improved.</p></div><div className="nextted-case-block"><h3>Outcome</h3><p>We translated the findings into the UX and UI design. App development is now approaching completion.</p></div></div></article>
  <article id="lightsync" className="nextted-case"><div className="nextted-case-meta"><span>03 · LightSync</span><span>Sports Technology / Product</span></div><h2>Making the audience part of the game.</h2><p className="nextted-case-intro">LightSync came from years of working inside professional sports events. After seeing the game from the production side, we wanted to build a product that could change how fans participate — not just watch.</p><div className="nextted-case-grid"><div className="nextted-case-block"><h3>Where it came from</h3><p>Our team has worked across Gaziantep Basketbol, Adam Voleybol, Gaziantep FK and, for 2026–2027, KBB Kipaş İstiklal Basketbol.</p></div><div className="nextted-case-block"><h3>More than lights</h3><p>The synchronized phone light is only one part. Polls, questions and live interactions are central to making the crowd an active part of the experience.</p></div><div className="nextted-case-block"><h3>The ambition</h3><p>Start in Türkiye, prove the experience in real venues and build toward a new standard for sports audience engagement.</p></div></div><div className="nextted-actions"><Link to="/admin" className="nextted-btn nextted-btn-primary">Open LightSync</Link></div></article>
</section></main><footer className="nextted-footer"><div className="nextted-container nextted-footer-inner"><span>© {new Date().getFullYear()} Nextted</span><span>Technology. Education. Design.</span></div></footer></div>; }
