import { Link } from 'react-router-dom';
import '../styles/nextted.css';

function Nav() { return <header className="nextted-nav"><Link to="/" className="nextted-logo">NEXTT<span>ED</span></Link><nav className="nextted-nav-links"><Link to="/mission">Misyon & Vizyon</Link><Link to="/projects">Projeler</Link><Link to="/contact">İletişim</Link><Link to="/admin" className="nextted-light-btn">LightSync'i Aç</Link></nav></header>; }

export default function Projects() { return <div className="nextted-site"><Nav /><main><section className="nextted-page-head"><div className="nextted-container"><p className="nextted-kicker">Seçili çalışmalar</p><h1>Gerçek kullanıcılar ve gerçek ortamlar etrafında geliştirilmiş projeler.</h1><p>Bu projeler sektör ve ölçek olarak farklı olsa da aynı yaklaşımı paylaşır: iş akışını anlayın, insanları anlayın, sonra ürünü tasarlayın.</p></div></section><section className="nextted-container">
  <article id="koza" className="nextted-case"><div className="nextted-case-meta"><span>01 · Koza Halı</span><span>Ürün Tasarımı / UX/UI</span></div><h2>Gerçek iş akışı etrafında tasarlanmış bir B2B deneyimi.</h2><p className="nextted-case-intro">Calvin Klein üreticisi ve distribütörü Koza Halı için mesele yalnızca daha güzel bir arayüz tasarlamak değildi. B2B operasyonunun nasıl yürüdüğünü analiz ettik ve bu anlayışla uygulamayı daha kolay kullanılabilir hale getirdik.</p><div className="nextted-case-grid"><div className="nextted-case-block"><h3>İş akışı analizi</h3><p>Kullanıcıların ne yapması gerektiğini, adımlar arasında nasıl ilerlediklerini ve dijital deneyimin nerelerde sürtünme yarattığını anlamak için mevcut süreci analiz ettik.</p></div><div className="nextted-case-block"><h3>Kullanıcı deneyimi</h3><p>Uygulamanın yapısını, kullanıcıları arayüze uyum sağlamaya zorlamak yerine insanların gerçekte çalışma biçimine göre yeniden tasarladık.</p></div><div className="nextted-case-block"><h3>Sonuç</h3><p>Nextted olarak B2B uygulamasının UX ve UI tasarımını hazırladık. Ürün şu anda aktif olarak kullanılıyor.</p></div></div></article>
  <article id="enyakit" className="nextted-case"><div className="nextted-case-meta"><span>02 · En Yakıt</span><span>UX Araştırması / UX/UI</span></div><h2>Elektrikli araç şarj yolculuğunu sahadan başlayarak tasarlamak.</h2><p className="nextted-case-intro">En Yakıt için yalnızca uygulama ekranlarına değil, uçtan uca şarj deneyimine baktık. Kullanıcı yolculuğu, şarj akışı ve şirketin THY iş birliği etrafındaki deneyim dahil olmak üzere sürecin tamamını ele aldık.</p><div className="nextted-case-grid"><div className="nextted-case-block"><h3>Uygulama haritalama</h3><p>Uygulamanın nasıl çalıştığını ve farklı kullanıcı yolculuklarının nasıl bağlandığını, THY iş birliğinin getirdiği ek bağlamı da dikkate alarak haritaladık.</p></div><div className="nextted-case-block"><h3>Saha araştırması</h3><p>Elektrikli araç şarj istasyonlarını kullanan insanların gerçekte ne yaşadığını ve dijital deneyimin nerelerde iyileştirilebileceğini anlamak için sahaya çıktık.</p></div><div className="nextted-case-block"><h3>Sonuç</h3><p>Bulguları UX ve UI tasarımına dönüştürdük. Uygulamanın geliştirme süreci tamamlanmak üzere.</p></div></div></article>
  <article id="lightsync" className="nextted-case"><div className="nextted-case-meta"><span>03 · LightSync</span><span>Spor Teknolojisi / Ürün</span></div><h2>Taraftarı oyunun bir parçası haline getirmek.</h2><p className="nextted-case-intro">LightSync, profesyonel spor etkinliklerinin içinde geçirdiğimiz yıllardan doğdu. Maçı prodüksiyon tarafından gördükten sonra taraftarların yalnızca izlemekle kalmayıp nasıl aktif şekilde katılabileceğini değiştirecek bir ürün geliştirmek istedik.</p><div className="nextted-case-grid"><div className="nextted-case-block"><h3>Nereden doğdu?</h3><p>Ekibimiz Gaziantep Basketbol, Adam Voleybol, Gaziantep FK ve 2026–2027 sezonunda KBB Kipaş İstiklal Basketbol ile çalıştı.</p></div><div className="nextted-case-block"><h3>Işıktan daha fazlası</h3><p>Senkronize telefon ışığı bunun yalnızca bir parçası. Anketler, sorular ve canlı etkileşimler kalabalığı deneyimin aktif bir parçası haline getirmenin merkezinde.</p></div><div className="nextted-case-block"><h3>Hedef</h3><p>Türkiye'de başlamak, gerçek salonlarda deneyimi kanıtlamak ve spor taraftar etkileşimi için yeni bir standart oluşturmak.</p></div></div><div className="nextted-actions"><Link to="/admin" className="nextted-btn nextted-btn-primary">LightSync'i Aç</Link></div></article>
</section></main><footer className="nextted-footer"><div className="nextted-container nextted-footer-inner"><span>© {new Date().getFullYear()} Nextted</span><span>Technology. Education. Design.</span></div></footer></div>; }
