import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ensureAnonymousAuth } from '../firebase/auth';
import { watchSportsInteractions, submitSportsResponse, type SportsInteraction } from '../firebase/sports';

export default function SportsFan() {
  const navigate = useNavigate(); const { eventId } = useParams();
  const [interaction, setInteraction] = useState<SportsInteraction | null>(null); const [uid, setUid] = useState<string | null>(null); const [selected, setSelected] = useState(''); const [answer, setAnswer] = useState(''); const [error, setError] = useState(''); const [sending, setSending] = useState(false);
  useEffect(() => { void ensureAnonymousAuth().then(user => setUid(user.uid)).catch(() => setError('Could not connect. Please refresh.')); }, []);
  useEffect(() => { if (!eventId) return; return watchSportsInteractions(eventId, items => setInteraction(items.find(item => item.status === 'open') ?? null)); }, [eventId]);
  async function submit() { if (!eventId || !uid || !interaction || sending) return; if (interaction.type === 'poll' && !selected) return setError('Choose an answer.'); if (interaction.type === 'question' && !answer.trim()) return setError('Enter an answer.'); setError(''); setSending(true); try { await submitSportsResponse(eventId, interaction.id, uid, interaction.type === 'poll' ? { optionId: selected } : { answer: answer.trim().slice(0, 200) }); navigate(`/join/${eventId}`, { replace: true }); } catch (err) { console.error(err); setError('Could not submit your answer.'); setSending(false); } }
  if (!eventId) return null;
  if (!interaction) return <main className="light-page"><div className="light-content"><div className="light-logo">LIGHTSYNC</div><div className="waiting-message">NO ACTIVE QUESTION</div><p className="waiting-description">Wait for the organizer to open the next interaction.</p><button className="light-join-button" onClick={() => navigate(`/join/${eventId}`)}>BACK TO SHOW</button></div></main>;
  return <main className="light-page"><div className="light-content" style={{ maxWidth: 620, width: '92vw' }}><div className="light-logo">LIGHTSYNC</div><div className="light-event-name" style={{ whiteSpace: 'normal' }}>{interaction.question}</div><div style={{ display: 'grid', gap: 12, marginTop: 28, width: '100%' }}>{interaction.type === 'poll' ? Object.entries(interaction.options ?? {}).map(([id, label]) => <button key={id} className="light-join-button" style={{ fontSize: 18, margin: 0 }} onClick={() => setSelected(id)}>{label}{selected === id ? ' ✓' : ''}</button>) : <textarea value={answer} onChange={e => setAnswer(e.target.value)} maxLength={200} placeholder="Type your answer..." rows={4} style={{ width: '100%', borderRadius: 16, padding: 16, fontSize: 18 }} />}</div><button className="light-join-button" style={{ marginTop: 18 }} disabled={sending} onClick={() => void submit()}>{sending ? 'SUBMITTING...' : 'SUBMIT'}</button><button type="button" onClick={() => navigate(`/join/${eventId}`)} style={{ marginTop: 10, background: 'transparent', border: 0, color: 'inherit', opacity: .7, fontWeight: 800, cursor: 'pointer' }}>← BACK TO SHOW</button>{error && <p className="light-error">{error}</p>}</div></main>;
}
